version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
<<<<<<< Updated upstream
    ports:
      - "4000:4000"
=======
    ports: 
      - '9090:9090'
>>>>>>> Stashed changes
    volumes:
      - ./api:/app
      - ./app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_c
    ports:
      - "9090:9090"
    stdin_open: true
    tty: true
